{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!pip3 install twilio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "from twilio.rest import Client\n",
    "import time\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "import pandas as pd\n",
    "import requests\n",
    "from bs4  import BeautifulSoup\n",
    "from tqdm import tqdm\n",
    "\n",
    "from datetime import datetime\n",
    "\n",
    "load_dotenv()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Armado de la URL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'http://api.weatherapi.com/v1/forecast.json?key=f4231736355b4bb7b4821948232209&q=Medellín&days=1&aqi=no&alerts=no'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query = 'Medellín'\n",
    "api_key = os.getenv('API_KEY_WAPI')\n",
    "\n",
    "url_clima = 'http://api.weatherapi.com/v1/forecast.json?key='+api_key+'&q='+query+'&days=1&aqi=no&alerts=no'\n",
    "url_clima"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "response = requests.get(url_clima).json()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'location': {'name': 'Medellín',\n",
       "  'region': 'Antioquia',\n",
       "  'country': 'Kolumbien',\n",
       "  'lat': 6.29,\n",
       "  'lon': -75.54,\n",
       "  'tz_id': 'America/Bogota',\n",
       "  'localtime_epoch': 1695406721,\n",
       "  'localtime': '2023-09-22 13:18'},\n",
       " 'current': {'last_updated_epoch': 1695406500,\n",
       "  'last_updated': '2023-09-22 13:15',\n",
       "  'temp_c': 32.0,\n",
       "  'temp_f': 89.6,\n",
       "  'is_day': 1,\n",
       "  'condition': {'text': 'Partly cloudy',\n",
       "   'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',\n",
       "   'code': 1003},\n",
       "  'wind_mph': 11.9,\n",
       "  'wind_kph': 19.1,\n",
       "  'wind_degree': 40,\n",
       "  'wind_dir': 'NE',\n",
       "  'pressure_mb': 1015.0,\n",
       "  'pressure_in': 29.97,\n",
       "  'precip_mm': 0.19,\n",
       "  'precip_in': 0.01,\n",
       "  'humidity': 32,\n",
       "  'cloud': 50,\n",
       "  'feelslike_c': 33.8,\n",
       "  'feelslike_f': 92.9,\n",
       "  'vis_km': 10.0,\n",
       "  'vis_miles': 6.0,\n",
       "  'uv': 5.0,\n",
       "  'gust_mph': 0.3,\n",
       "  'gust_kph': 0.4},\n",
       " 'forecast': {'forecastday': [{'date': '2023-09-22',\n",
       "    'date_epoch': 1695340800,\n",
       "    'day': {'maxtemp_c': 25.7,\n",
       "     'maxtemp_f': 78.2,\n",
       "     'mintemp_c': 12.1,\n",
       "     'mintemp_f': 53.8,\n",
       "     'avgtemp_c': 17.2,\n",
       "     'avgtemp_f': 63.0,\n",
       "     'maxwind_mph': 4.5,\n",
       "     'maxwind_kph': 7.2,\n",
       "     'totalprecip_mm': 8.66,\n",
       "     'totalprecip_in': 0.34,\n",
       "     'totalsnow_cm': 0.0,\n",
       "     'avgvis_km': 8.6,\n",
       "     'avgvis_miles': 5.0,\n",
       "     'avghumidity': 78.0,\n",
       "     'daily_will_it_rain': 1,\n",
       "     'daily_chance_of_rain': 90,\n",
       "     'daily_will_it_snow': 0,\n",
       "     'daily_chance_of_snow': 0,\n",
       "     'condition': {'text': 'Moderate rain',\n",
       "      'icon': '//cdn.weatherapi.com/weather/64x64/day/302.png',\n",
       "      'code': 1189},\n",
       "     'uv': 4.0},\n",
       "    'astro': {'sunrise': '05:52 AM',\n",
       "     'sunset': '05:58 PM',\n",
       "     'moonrise': '12:03 PM',\n",
       "     'moonset': 'No moonset',\n",
       "     'moon_phase': 'First Quarter',\n",
       "     'moon_illumination': '41',\n",
       "     'is_moon_up': 1,\n",
       "     'is_sun_up': 0},\n",
       "    'hour': [{'time_epoch': 1695358800,\n",
       "      'time': '2023-09-22 00:00',\n",
       "      'temp_c': 13.0,\n",
       "      'temp_f': 55.4,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Mist',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',\n",
       "       'code': 1030},\n",
       "      'wind_mph': 2.2,\n",
       "      'wind_kph': 3.6,\n",
       "      'wind_degree': 69,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.97,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 95,\n",
       "      'cloud': 44,\n",
       "      'feelslike_c': 13.6,\n",
       "      'feelslike_f': 56.4,\n",
       "      'windchill_c': 13.6,\n",
       "      'windchill_f': 56.4,\n",
       "      'heatindex_c': 13.0,\n",
       "      'heatindex_f': 55.4,\n",
       "      'dewpoint_c': 12.2,\n",
       "      'dewpoint_f': 53.9,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 2.0,\n",
       "      'vis_miles': 1.0,\n",
       "      'gust_mph': 4.7,\n",
       "      'gust_kph': 7.6,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695362400,\n",
       "      'time': '2023-09-22 01:00',\n",
       "      'temp_c': 12.7,\n",
       "      'temp_f': 54.9,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.5,\n",
       "      'wind_kph': 4.0,\n",
       "      'wind_degree': 79,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.95,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 94,\n",
       "      'cloud': 40,\n",
       "      'feelslike_c': 13.2,\n",
       "      'feelslike_f': 55.7,\n",
       "      'windchill_c': 13.2,\n",
       "      'windchill_f': 55.7,\n",
       "      'heatindex_c': 12.7,\n",
       "      'heatindex_f': 54.9,\n",
       "      'dewpoint_c': 11.8,\n",
       "      'dewpoint_f': 53.2,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.2,\n",
       "      'gust_kph': 8.3,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695366000,\n",
       "      'time': '2023-09-22 02:00',\n",
       "      'temp_c': 12.5,\n",
       "      'temp_f': 54.5,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.5,\n",
       "      'wind_kph': 4.0,\n",
       "      'wind_degree': 73,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.93,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 94,\n",
       "      'cloud': 36,\n",
       "      'feelslike_c': 12.9,\n",
       "      'feelslike_f': 55.2,\n",
       "      'windchill_c': 12.9,\n",
       "      'windchill_f': 55.2,\n",
       "      'heatindex_c': 12.5,\n",
       "      'heatindex_f': 54.5,\n",
       "      'dewpoint_c': 11.5,\n",
       "      'dewpoint_f': 52.6,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.2,\n",
       "      'gust_kph': 8.3,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695369600,\n",
       "      'time': '2023-09-22 03:00',\n",
       "      'temp_c': 12.2,\n",
       "      'temp_f': 54.0,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 76,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.93,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 93,\n",
       "      'cloud': 37,\n",
       "      'feelslike_c': 12.5,\n",
       "      'feelslike_f': 54.5,\n",
       "      'windchill_c': 12.5,\n",
       "      'windchill_f': 54.5,\n",
       "      'heatindex_c': 12.2,\n",
       "      'heatindex_f': 54.0,\n",
       "      'dewpoint_c': 11.2,\n",
       "      'dewpoint_f': 52.1,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.6,\n",
       "      'gust_kph': 9.1,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695373200,\n",
       "      'time': '2023-09-22 04:00',\n",
       "      'temp_c': 12.2,\n",
       "      'temp_f': 53.9,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 74,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.94,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 93,\n",
       "      'cloud': 33,\n",
       "      'feelslike_c': 12.4,\n",
       "      'feelslike_f': 54.3,\n",
       "      'windchill_c': 12.4,\n",
       "      'windchill_f': 54.3,\n",
       "      'heatindex_c': 12.2,\n",
       "      'heatindex_f': 53.9,\n",
       "      'dewpoint_c': 11.1,\n",
       "      'dewpoint_f': 51.9,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.6,\n",
       "      'gust_kph': 9.1,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695376800,\n",
       "      'time': '2023-09-22 05:00',\n",
       "      'temp_c': 12.0,\n",
       "      'temp_f': 53.5,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 81,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.96,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 94,\n",
       "      'cloud': 39,\n",
       "      'feelslike_c': 12.2,\n",
       "      'feelslike_f': 53.9,\n",
       "      'windchill_c': 12.2,\n",
       "      'windchill_f': 53.9,\n",
       "      'heatindex_c': 12.0,\n",
       "      'heatindex_f': 53.5,\n",
       "      'dewpoint_c': 11.0,\n",
       "      'dewpoint_f': 51.8,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.6,\n",
       "      'gust_kph': 9.1,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695380400,\n",
       "      'time': '2023-09-22 06:00',\n",
       "      'temp_c': 12.0,\n",
       "      'temp_f': 53.6,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Mist',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/143.png',\n",
       "       'code': 1030},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 90,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.97,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 94,\n",
       "      'cloud': 42,\n",
       "      'feelslike_c': 12.2,\n",
       "      'feelslike_f': 54.0,\n",
       "      'windchill_c': 12.2,\n",
       "      'windchill_f': 54.0,\n",
       "      'heatindex_c': 12.0,\n",
       "      'heatindex_f': 53.6,\n",
       "      'dewpoint_c': 11.1,\n",
       "      'dewpoint_f': 52.0,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 2.0,\n",
       "      'vis_miles': 1.0,\n",
       "      'gust_mph': 5.6,\n",
       "      'gust_kph': 9.1,\n",
       "      'uv': 3.0},\n",
       "     {'time_epoch': 1695384000,\n",
       "      'time': '2023-09-22 07:00',\n",
       "      'temp_c': 15.1,\n",
       "      'temp_f': 59.3,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.5,\n",
       "      'wind_kph': 4.0,\n",
       "      'wind_degree': 91,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.96,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 83,\n",
       "      'cloud': 27,\n",
       "      'feelslike_c': 15.2,\n",
       "      'feelslike_f': 59.3,\n",
       "      'windchill_c': 15.2,\n",
       "      'windchill_f': 59.3,\n",
       "      'heatindex_c': 15.2,\n",
       "      'heatindex_f': 59.3,\n",
       "      'dewpoint_c': 12.4,\n",
       "      'dewpoint_f': 54.2,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 3.9,\n",
       "      'gust_kph': 6.2,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695387600,\n",
       "      'time': '2023-09-22 08:00',\n",
       "      'temp_c': 18.8,\n",
       "      'temp_f': 65.9,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Sunny',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',\n",
       "       'code': 1000},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 97,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.94,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 66,\n",
       "      'cloud': 15,\n",
       "      'feelslike_c': 18.8,\n",
       "      'feelslike_f': 65.9,\n",
       "      'windchill_c': 18.8,\n",
       "      'windchill_f': 65.9,\n",
       "      'heatindex_c': 18.8,\n",
       "      'heatindex_f': 65.9,\n",
       "      'dewpoint_c': 12.3,\n",
       "      'dewpoint_f': 54.1,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 3.1,\n",
       "      'gust_kph': 5.0,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695391200,\n",
       "      'time': '2023-09-22 09:00',\n",
       "      'temp_c': 21.2,\n",
       "      'temp_f': 70.2,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 90,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1013.0,\n",
       "      'pressure_in': 29.93,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 55,\n",
       "      'cloud': 32,\n",
       "      'feelslike_c': 21.2,\n",
       "      'feelslike_f': 70.2,\n",
       "      'windchill_c': 21.2,\n",
       "      'windchill_f': 70.2,\n",
       "      'heatindex_c': 24.4,\n",
       "      'heatindex_f': 75.9,\n",
       "      'dewpoint_c': 11.9,\n",
       "      'dewpoint_f': 53.4,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 3.1,\n",
       "      'gust_kph': 5.0,\n",
       "      'uv': 6.0},\n",
       "     {'time_epoch': 1695394800,\n",
       "      'time': '2023-09-22 10:00',\n",
       "      'temp_c': 23.5,\n",
       "      'temp_f': 74.3,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 2.2,\n",
       "      'wind_kph': 3.6,\n",
       "      'wind_degree': 89,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1013.0,\n",
       "      'pressure_in': 29.9,\n",
       "      'precip_mm': 0.06,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 48,\n",
       "      'cloud': 77,\n",
       "      'feelslike_c': 24.9,\n",
       "      'feelslike_f': 76.8,\n",
       "      'windchill_c': 23.5,\n",
       "      'windchill_f': 74.3,\n",
       "      'heatindex_c': 24.9,\n",
       "      'heatindex_f': 76.8,\n",
       "      'dewpoint_c': 11.9,\n",
       "      'dewpoint_f': 53.4,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 68,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 2.6,\n",
       "      'gust_kph': 4.1,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695398400,\n",
       "      'time': '2023-09-22 11:00',\n",
       "      'temp_c': 24.9,\n",
       "      'temp_f': 76.8,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 1.8,\n",
       "      'wind_kph': 2.9,\n",
       "      'wind_degree': 95,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1011.0,\n",
       "      'pressure_in': 29.86,\n",
       "      'precip_mm': 0.13,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 43,\n",
       "      'cloud': 85,\n",
       "      'feelslike_c': 25.5,\n",
       "      'feelslike_f': 77.9,\n",
       "      'windchill_c': 24.9,\n",
       "      'windchill_f': 76.8,\n",
       "      'heatindex_c': 25.5,\n",
       "      'heatindex_f': 77.9,\n",
       "      'dewpoint_c': 11.7,\n",
       "      'dewpoint_f': 53.0,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 75,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 2.1,\n",
       "      'gust_kph': 3.3,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695402000,\n",
       "      'time': '2023-09-22 12:00',\n",
       "      'temp_c': 25.5,\n",
       "      'temp_f': 77.9,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 1.6,\n",
       "      'wind_kph': 2.5,\n",
       "      'wind_degree': 95,\n",
       "      'wind_dir': 'E',\n",
       "      'pressure_mb': 1009.0,\n",
       "      'pressure_in': 29.81,\n",
       "      'precip_mm': 0.14,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 42,\n",
       "      'cloud': 75,\n",
       "      'feelslike_c': 25.8,\n",
       "      'feelslike_f': 78.5,\n",
       "      'windchill_c': 25.5,\n",
       "      'windchill_f': 77.9,\n",
       "      'heatindex_c': 25.8,\n",
       "      'heatindex_f': 78.5,\n",
       "      'dewpoint_c': 11.7,\n",
       "      'dewpoint_f': 53.0,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 69,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 1.8,\n",
       "      'gust_kph': 2.9,\n",
       "      'uv': 6.0},\n",
       "     {'time_epoch': 1695405600,\n",
       "      'time': '2023-09-22 13:00',\n",
       "      'temp_c': 32.0,\n",
       "      'temp_f': 89.6,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Partly cloudy',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',\n",
       "       'code': 1003},\n",
       "      'wind_mph': 11.9,\n",
       "      'wind_kph': 19.1,\n",
       "      'wind_degree': 40,\n",
       "      'wind_dir': 'NE',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.97,\n",
       "      'precip_mm': 0.19,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 32,\n",
       "      'cloud': 50,\n",
       "      'feelslike_c': 25.3,\n",
       "      'feelslike_f': 77.5,\n",
       "      'windchill_c': 24.5,\n",
       "      'windchill_f': 76.1,\n",
       "      'heatindex_c': 25.3,\n",
       "      'heatindex_f': 77.5,\n",
       "      'dewpoint_c': 11.8,\n",
       "      'dewpoint_f': 53.2,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 67,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 0.3,\n",
       "      'gust_kph': 0.4,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695409200,\n",
       "      'time': '2023-09-22 14:00',\n",
       "      'temp_c': 23.8,\n",
       "      'temp_f': 74.8,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 1.3,\n",
       "      'wind_kph': 2.2,\n",
       "      'wind_degree': 297,\n",
       "      'wind_dir': 'WNW',\n",
       "      'pressure_mb': 1007.0,\n",
       "      'pressure_in': 29.74,\n",
       "      'precip_mm': 0.19,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 51,\n",
       "      'cloud': 85,\n",
       "      'feelslike_c': 25.1,\n",
       "      'feelslike_f': 77.2,\n",
       "      'windchill_c': 23.8,\n",
       "      'windchill_f': 74.8,\n",
       "      'heatindex_c': 25.1,\n",
       "      'heatindex_f': 77.2,\n",
       "      'dewpoint_c': 12.9,\n",
       "      'dewpoint_f': 55.3,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 64,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 1.7,\n",
       "      'gust_kph': 2.7,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695412800,\n",
       "      'time': '2023-09-22 15:00',\n",
       "      'temp_c': 23.7,\n",
       "      'temp_f': 74.7,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 1.8,\n",
       "      'wind_kph': 2.9,\n",
       "      'wind_degree': 0,\n",
       "      'wind_dir': 'N',\n",
       "      'pressure_mb': 1006.0,\n",
       "      'pressure_in': 29.72,\n",
       "      'precip_mm': 0.24,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 50,\n",
       "      'cloud': 76,\n",
       "      'feelslike_c': 25.1,\n",
       "      'feelslike_f': 77.1,\n",
       "      'windchill_c': 23.8,\n",
       "      'windchill_f': 74.8,\n",
       "      'heatindex_c': 25.1,\n",
       "      'heatindex_f': 77.1,\n",
       "      'dewpoint_c': 12.8,\n",
       "      'dewpoint_f': 55.1,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 68,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 2.2,\n",
       "      'gust_kph': 3.5,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695416400,\n",
       "      'time': '2023-09-22 16:00',\n",
       "      'temp_c': 21.3,\n",
       "      'temp_f': 70.4,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 45,\n",
       "      'wind_dir': 'NE',\n",
       "      'pressure_mb': 1007.0,\n",
       "      'pressure_in': 29.74,\n",
       "      'precip_mm': 0.25,\n",
       "      'precip_in': 0.01,\n",
       "      'humidity': 63,\n",
       "      'cloud': 73,\n",
       "      'feelslike_c': 21.3,\n",
       "      'feelslike_f': 70.4,\n",
       "      'windchill_c': 21.3,\n",
       "      'windchill_f': 70.4,\n",
       "      'heatindex_c': 24.5,\n",
       "      'heatindex_f': 76.0,\n",
       "      'dewpoint_c': 14.0,\n",
       "      'dewpoint_f': 57.1,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 64,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 4.4,\n",
       "      'gust_kph': 7.1,\n",
       "      'uv': 5.0},\n",
       "     {'time_epoch': 1695420000,\n",
       "      'time': '2023-09-22 17:00',\n",
       "      'temp_c': 17.7,\n",
       "      'temp_f': 63.9,\n",
       "      'is_day': 1,\n",
       "      'condition': {'text': 'Patchy rain possible',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',\n",
       "       'code': 1063},\n",
       "      'wind_mph': 3.4,\n",
       "      'wind_kph': 5.4,\n",
       "      'wind_degree': 58,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1009.0,\n",
       "      'pressure_in': 29.8,\n",
       "      'precip_mm': 0.11,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 83,\n",
       "      'cloud': 88,\n",
       "      'feelslike_c': 17.7,\n",
       "      'feelslike_f': 63.9,\n",
       "      'windchill_c': 17.7,\n",
       "      'windchill_f': 63.9,\n",
       "      'heatindex_c': 17.7,\n",
       "      'heatindex_f': 63.9,\n",
       "      'dewpoint_c': 14.8,\n",
       "      'dewpoint_f': 58.7,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 73,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 7.0,\n",
       "      'gust_kph': 11.3,\n",
       "      'uv': 4.0},\n",
       "     {'time_epoch': 1695423600,\n",
       "      'time': '2023-09-22 18:00',\n",
       "      'temp_c': 16.1,\n",
       "      'temp_f': 61.0,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Light rain shower',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',\n",
       "       'code': 1240},\n",
       "      'wind_mph': 2.7,\n",
       "      'wind_kph': 4.3,\n",
       "      'wind_degree': 61,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1010.0,\n",
       "      'pressure_in': 29.83,\n",
       "      'precip_mm': 1.92,\n",
       "      'precip_in': 0.08,\n",
       "      'humidity': 91,\n",
       "      'cloud': 75,\n",
       "      'feelslike_c': 16.1,\n",
       "      'feelslike_f': 61.0,\n",
       "      'windchill_c': 16.1,\n",
       "      'windchill_f': 61.0,\n",
       "      'heatindex_c': 16.1,\n",
       "      'heatindex_f': 61.0,\n",
       "      'dewpoint_c': 14.6,\n",
       "      'dewpoint_f': 58.3,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 71,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 5.6,\n",
       "      'gust_kph': 9.1,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695427200,\n",
       "      'time': '2023-09-22 19:00',\n",
       "      'temp_c': 14.6,\n",
       "      'temp_f': 58.3,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Patchy light rain',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/293.png',\n",
       "       'code': 1180},\n",
       "      'wind_mph': 2.0,\n",
       "      'wind_kph': 3.2,\n",
       "      'wind_degree': 71,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1012.0,\n",
       "      'pressure_in': 29.88,\n",
       "      'precip_mm': 2.26,\n",
       "      'precip_in': 0.09,\n",
       "      'humidity': 95,\n",
       "      'cloud': 51,\n",
       "      'feelslike_c': 15.5,\n",
       "      'feelslike_f': 59.9,\n",
       "      'windchill_c': 15.5,\n",
       "      'windchill_f': 59.9,\n",
       "      'heatindex_c': 14.6,\n",
       "      'heatindex_f': 58.3,\n",
       "      'dewpoint_c': 13.9,\n",
       "      'dewpoint_f': 57.0,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 90,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 9.0,\n",
       "      'vis_miles': 5.0,\n",
       "      'gust_mph': 4.2,\n",
       "      'gust_kph': 6.8,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695430800,\n",
       "      'time': '2023-09-22 20:00',\n",
       "      'temp_c': 14.3,\n",
       "      'temp_f': 57.8,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Light rain shower',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',\n",
       "       'code': 1240},\n",
       "      'wind_mph': 1.6,\n",
       "      'wind_kph': 2.5,\n",
       "      'wind_degree': 185,\n",
       "      'wind_dir': 'S',\n",
       "      'pressure_mb': 1014.0,\n",
       "      'pressure_in': 29.95,\n",
       "      'precip_mm': 2.49,\n",
       "      'precip_in': 0.1,\n",
       "      'humidity': 97,\n",
       "      'cloud': 71,\n",
       "      'feelslike_c': 14.3,\n",
       "      'feelslike_f': 57.8,\n",
       "      'windchill_c': 14.3,\n",
       "      'windchill_f': 57.8,\n",
       "      'heatindex_c': 14.3,\n",
       "      'heatindex_f': 57.8,\n",
       "      'dewpoint_c': 13.9,\n",
       "      'dewpoint_f': 56.9,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 93,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 10.0,\n",
       "      'vis_miles': 6.0,\n",
       "      'gust_mph': 3.3,\n",
       "      'gust_kph': 5.3,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695434400,\n",
       "      'time': '2023-09-22 21:00',\n",
       "      'temp_c': 14.2,\n",
       "      'temp_f': 57.6,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Mist',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',\n",
       "       'code': 1030},\n",
       "      'wind_mph': 1.8,\n",
       "      'wind_kph': 2.9,\n",
       "      'wind_degree': 198,\n",
       "      'wind_dir': 'SSW',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.97,\n",
       "      'precip_mm': 0.04,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 97,\n",
       "      'cloud': 66,\n",
       "      'feelslike_c': 14.2,\n",
       "      'feelslike_f': 57.6,\n",
       "      'windchill_c': 14.2,\n",
       "      'windchill_f': 57.6,\n",
       "      'heatindex_c': 14.2,\n",
       "      'heatindex_f': 57.6,\n",
       "      'dewpoint_c': 13.8,\n",
       "      'dewpoint_f': 56.8,\n",
       "      'will_it_rain': 1,\n",
       "      'chance_of_rain': 87,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 2.0,\n",
       "      'vis_miles': 1.0,\n",
       "      'gust_mph': 3.8,\n",
       "      'gust_kph': 6.0,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695438000,\n",
       "      'time': '2023-09-22 22:00',\n",
       "      'temp_c': 14.0,\n",
       "      'temp_f': 57.2,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Mist',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',\n",
       "       'code': 1030},\n",
       "      'wind_mph': 0.9,\n",
       "      'wind_kph': 1.4,\n",
       "      'wind_degree': 62,\n",
       "      'wind_dir': 'ENE',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.98,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 97,\n",
       "      'cloud': 58,\n",
       "      'feelslike_c': 14.0,\n",
       "      'feelslike_f': 57.3,\n",
       "      'windchill_c': 14.0,\n",
       "      'windchill_f': 57.3,\n",
       "      'heatindex_c': 14.0,\n",
       "      'heatindex_f': 57.3,\n",
       "      'dewpoint_c': 13.5,\n",
       "      'dewpoint_f': 56.3,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 2.0,\n",
       "      'vis_miles': 1.0,\n",
       "      'gust_mph': 1.9,\n",
       "      'gust_kph': 3.0,\n",
       "      'uv': 1.0},\n",
       "     {'time_epoch': 1695441600,\n",
       "      'time': '2023-09-22 23:00',\n",
       "      'temp_c': 13.8,\n",
       "      'temp_f': 56.8,\n",
       "      'is_day': 0,\n",
       "      'condition': {'text': 'Mist',\n",
       "       'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',\n",
       "       'code': 1030},\n",
       "      'wind_mph': 1.8,\n",
       "      'wind_kph': 2.9,\n",
       "      'wind_degree': 1,\n",
       "      'wind_dir': 'N',\n",
       "      'pressure_mb': 1015.0,\n",
       "      'pressure_in': 29.98,\n",
       "      'precip_mm': 0.0,\n",
       "      'precip_in': 0.0,\n",
       "      'humidity': 97,\n",
       "      'cloud': 58,\n",
       "      'feelslike_c': 13.8,\n",
       "      'feelslike_f': 56.8,\n",
       "      'windchill_c': 13.8,\n",
       "      'windchill_f': 56.8,\n",
       "      'heatindex_c': 13.8,\n",
       "      'heatindex_f': 56.8,\n",
       "      'dewpoint_c': 13.3,\n",
       "      'dewpoint_f': 55.9,\n",
       "      'will_it_rain': 0,\n",
       "      'chance_of_rain': 0,\n",
       "      'will_it_snow': 0,\n",
       "      'chance_of_snow': 0,\n",
       "      'vis_km': 2.0,\n",
       "      'vis_miles': 1.0,\n",
       "      'gust_mph': 3.8,\n",
       "      'gust_kph': 6.0,\n",
       "      'uv': 1.0}]}]}}"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['location', 'current', 'forecast'])"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['date', 'date_epoch', 'day', 'astro', 'hour'])"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0].keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "24"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(response['forecast']['forecastday'][0]['hour'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2023-09-22 00:00'"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][0]['time']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2023-09-22'"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][0]['time'].split()[0] # fecha"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "int(response['forecast']['forecastday'][0]['hour'][1]['time'].split()[1].split(':')[0]) # hora"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Mist'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][0]['condition']['text'] # condición"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "13.0"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][0]['temp_c'] # temperatura"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][2]['will_it_rain']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response['forecast']['forecastday'][0]['hour'][2]['chance_of_rain']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_forecast(response,i):\n",
    "    \n",
    "    fecha = response['forecast']['forecastday'][0]['hour'][i]['time'].split()[0]\n",
    "    hora = int(response['forecast']['forecastday'][0]['hour'][i]['time'].split()[1].split(':')[0])\n",
    "    condicion = response['forecast']['forecastday'][0]['hour'][i]['condition']['text']\n",
    "    tempe = float(response['forecast']['forecastday'][0]['hour'][i]['temp_c'])\n",
    "    rain = response['forecast']['forecastday'][0]['hour'][i]['will_it_rain']\n",
    "    prob_rain = response['forecast']['forecastday'][0]['hour'][i]['chance_of_rain']\n",
    "    \n",
    "    return fecha,hora,condicion,tempe,rain,prob_rain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|\u001b[32m██████████\u001b[0m| 24/24 [00:00<00:00, 24267.91it/s]\n"
     ]
    }
   ],
   "source": [
    "datos = []\n",
    "\n",
    "for i in tqdm(range(len(response['forecast']['forecastday'][0]['hour'])),colour = 'green'):\n",
    "    \n",
    "    datos.append(get_forecast(response,i))\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "('2023-09-22', 0, 'Mist', 13.0, 0, 0)"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "datos[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Fecha</th>\n",
       "      <th>Hora</th>\n",
       "      <th>Condicion</th>\n",
       "      <th>Temperatura</th>\n",
       "      <th>Lluvia</th>\n",
       "      <th>prob_lluvia</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>0</td>\n",
       "      <td>Mist</td>\n",
       "      <td>13.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>1</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>12.7</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>2</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>12.5</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>3</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>12.2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>4</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>12.2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>5</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>12.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>6</td>\n",
       "      <td>Mist</td>\n",
       "      <td>12.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>7</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>15.1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>8</td>\n",
       "      <td>Sunny</td>\n",
       "      <td>18.8</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>9</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>21.2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>10</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>23.5</td>\n",
       "      <td>0</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>11</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>24.9</td>\n",
       "      <td>1</td>\n",
       "      <td>75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>12</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>25.5</td>\n",
       "      <td>0</td>\n",
       "      <td>69</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>13</td>\n",
       "      <td>Partly cloudy</td>\n",
       "      <td>32.0</td>\n",
       "      <td>0</td>\n",
       "      <td>67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>14</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>23.8</td>\n",
       "      <td>0</td>\n",
       "      <td>64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>15</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>23.7</td>\n",
       "      <td>0</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>16</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>21.3</td>\n",
       "      <td>0</td>\n",
       "      <td>64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>17</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>17.7</td>\n",
       "      <td>1</td>\n",
       "      <td>73</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>18</td>\n",
       "      <td>Light rain shower</td>\n",
       "      <td>16.1</td>\n",
       "      <td>1</td>\n",
       "      <td>71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>19</td>\n",
       "      <td>Patchy light rain</td>\n",
       "      <td>14.6</td>\n",
       "      <td>1</td>\n",
       "      <td>90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>20</td>\n",
       "      <td>Light rain shower</td>\n",
       "      <td>14.3</td>\n",
       "      <td>1</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>21</td>\n",
       "      <td>Mist</td>\n",
       "      <td>14.2</td>\n",
       "      <td>1</td>\n",
       "      <td>87</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>22</td>\n",
       "      <td>Mist</td>\n",
       "      <td>14.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>23</td>\n",
       "      <td>Mist</td>\n",
       "      <td>13.8</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Fecha  Hora             Condicion  Temperatura  Lluvia  prob_lluvia\n",
       "0   2023-09-22     0                  Mist         13.0       0            0\n",
       "1   2023-09-22     1         Partly cloudy         12.7       0            0\n",
       "2   2023-09-22     2         Partly cloudy         12.5       0            0\n",
       "3   2023-09-22     3         Partly cloudy         12.2       0            0\n",
       "4   2023-09-22     4         Partly cloudy         12.2       0            0\n",
       "5   2023-09-22     5         Partly cloudy         12.0       0            0\n",
       "6   2023-09-22     6                  Mist         12.0       0            0\n",
       "7   2023-09-22     7         Partly cloudy         15.1       0            0\n",
       "8   2023-09-22     8                 Sunny         18.8       0            0\n",
       "9   2023-09-22     9         Partly cloudy         21.2       0            0\n",
       "10  2023-09-22    10  Patchy rain possible         23.5       0           68\n",
       "11  2023-09-22    11  Patchy rain possible         24.9       1           75\n",
       "12  2023-09-22    12  Patchy rain possible         25.5       0           69\n",
       "13  2023-09-22    13         Partly cloudy         32.0       0           67\n",
       "14  2023-09-22    14  Patchy rain possible         23.8       0           64\n",
       "15  2023-09-22    15  Patchy rain possible         23.7       0           68\n",
       "16  2023-09-22    16  Patchy rain possible         21.3       0           64\n",
       "17  2023-09-22    17  Patchy rain possible         17.7       1           73\n",
       "18  2023-09-22    18     Light rain shower         16.1       1           71\n",
       "19  2023-09-22    19     Patchy light rain         14.6       1           90\n",
       "20  2023-09-22    20     Light rain shower         14.3       1           93\n",
       "21  2023-09-22    21                  Mist         14.2       1           87\n",
       "22  2023-09-22    22                  Mist         14.0       0            0\n",
       "23  2023-09-22    23                  Mist         13.8       0            0"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "col = ['Fecha','Hora','Condicion','Temperatura','Lluvia','prob_lluvia']\n",
    "df = pd.DataFrame(datos,columns=col)\n",
    "df = df.sort_values(by = 'Hora',ascending = True)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "# data_cli = {\n",
    "#     'Fecha':datos[0][0],\n",
    "#     'Hora':datos[1][],\n",
    "#     'Tiempo':condicion,\n",
    "#     'Temperatura':tempe,\n",
    "#     'LLoverá':rain,\n",
    "#     'prob_lluvia':prob_rain\n",
    "    \n",
    "# }\n",
    "\n",
    "# df = pd.DataFrame(data_cli)\n",
    "# df = df.sort_values(by = 'Hora',ascending = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Fecha</th>\n",
       "      <th>Hora</th>\n",
       "      <th>Condicion</th>\n",
       "      <th>Temperatura</th>\n",
       "      <th>Lluvia</th>\n",
       "      <th>prob_lluvia</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>11</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>24.9</td>\n",
       "      <td>1</td>\n",
       "      <td>75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>17</td>\n",
       "      <td>Patchy rain possible</td>\n",
       "      <td>17.7</td>\n",
       "      <td>1</td>\n",
       "      <td>73</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>18</td>\n",
       "      <td>Light rain shower</td>\n",
       "      <td>16.1</td>\n",
       "      <td>1</td>\n",
       "      <td>71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>19</td>\n",
       "      <td>Patchy light rain</td>\n",
       "      <td>14.6</td>\n",
       "      <td>1</td>\n",
       "      <td>90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>20</td>\n",
       "      <td>Light rain shower</td>\n",
       "      <td>14.3</td>\n",
       "      <td>1</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>2023-09-22</td>\n",
       "      <td>21</td>\n",
       "      <td>Mist</td>\n",
       "      <td>14.2</td>\n",
       "      <td>1</td>\n",
       "      <td>87</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Fecha  Hora             Condicion  Temperatura  Lluvia  prob_lluvia\n",
       "11  2023-09-22    11  Patchy rain possible         24.9       1           75\n",
       "17  2023-09-22    17  Patchy rain possible         17.7       1           73\n",
       "18  2023-09-22    18     Light rain shower         16.1       1           71\n",
       "19  2023-09-22    19     Patchy light rain         14.6       1           90\n",
       "20  2023-09-22    20     Light rain shower         14.3       1           93\n",
       "21  2023-09-22    21                  Mist         14.2       1           87"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[df['Lluvia']==1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_rain =  df[(df['Lluvia']==1) & (df['Hora']>6) & (df['Hora']< 22)]\n",
    "df_rain = df_rain[['Hora','Condicion']]\n",
    "df_rain.set_index('Hora', inplace = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'2023-09-22'"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['Fecha'][0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Condicion</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Hora</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Patchy rain possible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Patchy rain possible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Light rain shower</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Patchy light rain</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Light rain shower</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Mist</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Condicion\n",
       "Hora                      \n",
       "11    Patchy rain possible\n",
       "17    Patchy rain possible\n",
       "18       Light rain shower\n",
       "19       Patchy light rain\n",
       "20       Light rain shower\n",
       "21                    Mist"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_rain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nHola! \\n\\n\\n El pronostico del tiempo hoy 2023-09-22 en Medellín es : \\n\\n\\n                  Condicion\\nHora                      \\n11    Patchy rain possible\\n17    Patchy rain possible\\n18       Light rain shower\\n19       Patchy light rain\\n20       Light rain shower\\n21                    Mist'"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'\\nHola! \\n\\n\\n El pronostico del tiempo hoy '+ df['Fecha'][0] +' en ' + query +' es : \\n\\n\\n ' + str(df_rain)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'+14056895542'"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.getenv('PHONE_NUMBER')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mensaje SMS desde Twilio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mensaje Enviado SM6d671068f99eac0cdf711f85fa155831\n"
     ]
    }
   ],
   "source": [
    "time.sleep(2)\n",
    "account_sid = os.getenv('TWILIO_ACCOUNT_SID') \n",
    "auth_token = os.getenv('TWILIO_AUTH_TOKEN')\n",
    "\n",
    "client = Client(account_sid, auth_token)\n",
    "\n",
    "message = client.messages \\\n",
    "                .create(\n",
    "                     body='\\nHola! \\n\\n\\n El pronostico de lluvia hoy '+ df['Fecha'][0] +' en ' + query +' es : \\n\\n\\n ' + str(df_rain),\n",
    "                     from_=os.getenv('PHONE_NUMBER'),\n",
    "                     to=os.getenv('MIO')\n",
    "                 )\n",
    "\n",
    "print('Mensaje Enviado ' + message.sid)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
